[package]
name = "brooks-geyser-plugin"
version = "0.1.0"
edition = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
agave-geyser-plugin-interface = { workspace = true }
agave-logger = { workspace = true }
log = { workspace = true }
solana-pubkey = { workspace = true }
